# Stage 1: Build and Train the Model
FROM python:3.10 AS model_training

WORKDIR /model_output

COPY src/model_training.py /model_output/
COPY requirements.txt /model_output/

RUN pip install -r requirements.txt
RUN python model_training.py


# Stage 2: Serve Predictions
FROM python:3.10 AS serving

WORKDIR /app

COPY --from=model_training /model_output/my_model.keras /app/my_model.keras
COPY src/main.py /app/
COPY requirements.txt /app/

RUN pip install --trusted-host pypi.python.org -r requirements.txt

COPY src/templates /app/templates   

EXPOSE 4000

CMD ["python", "main.py"]
